# Generated by Django 3.1 on 2021-05-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
